server:
  port: 8762
spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.1.13:8848
        server-addr: 192.168.61.129:8848
security:
  oauth2:
    client:
      client-id: xxxbApp
      client-secret: 123456
      access-token-uri: http://127.0.0.1:8766/oauth/token
      user-authorization-uri: http://127.0.0.1:8766/oauth/authorize
      scope: [all]
    resource:
      jwt:
        key-uri: http://127.0.0.1:8766/oauth/token_key
