server:
  port: 8762
  servlet:
    session:
      cookie:
        name: xxx
spring:
#  #集成elasticsearch
#  data:
#    elasticsearch:
#      #      repositories:
#      #        enabled: true
#      cluster-name: docker-cluster
#      cluster-nodes: 192.168.61.129:9300
#  elasticsearch:
#    rest:
#      uris: ["http://192.168.61.129:9200"]



  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.1.13:8848
        server-addr: 192.168.61.129:8848
  activemq:
#    broker-url: tcp://192.168.61.128:61616
    broker-url: nio://192.168.61.128:61111
    user: admin
    password: admin
  jms:
    pub-sub-domain: false #false为点对点  true为一对多(订阅)

queueStrName : queue

security:
  oauth2:
    client:
      client-id: xxxbApp
      client-secret: 123456
      access-token-uri: http://127.0.0.1:8766/oauth/token
      user-authorization-uri: http://127.0.0.1:8766/oauth/authorize
      scope: [all]
    resource:
      jwt:
        key-uri: http://127.0.0.1:8766/oauth/token_key
logging:
  level:
    root: error
    org.springframework.security: debug

