server:
  port: 8766
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: sso-server
#  当多个环境配置时选择哪个配置
#  profiles:
#    active: dev
  #集成elasticsearch
#  data:
#    elasticsearch:
##      repositories:
##        enabled: true
#      cluster-name: docker-cluster
#      cluster-nodes: 192.168.61.129:9300
#  elasticsearch:
#    rest:
#      uris: ["http://192.168.61.129:9200"]

  cloud:
    nacos:
      config:
        server-addr: 192.168.61.129:8848
      discovery:
        server-addr: 192.168.61.129:8848
  datasource:
    name: hikari
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.61.129:3306/xc_user?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  redis:
    host: 192.168.61.129
#    database: 0
#security:
#  oauth2:
#    authorization:
#      check-token-access: "isAuthenticated()"
#      token-key-access: "isAuthenticated()"

#security:
#  oauth2:
#    client:
#      client-id: XcWebApp
#      client-secret: $2a$10$9bEpZ/hWRQxyr5hn5wHUj.jxFpIrnOmBcWlE/g/0Zp3uNxt9QTh/S
#      access-token-uri: http://192.168.1.28:7100/oauth2/oauth/token
#      user-authorization-uri: http://192.168.1.28:7100/oauth2/oauth/authorize

#eureka:
#  client:
#    serverUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/

#日志
#logging:
#  config: classpath: logback.xml
#  level:
#    org:
#      springframework:
#        web: info
#  debug: true
